### ISSUE TITLE
Error occurred with using reusable workflows

### ISSUE THREAD

**Issue by nowsprinting** [pkgdeps/update-github-actions-permissions#30]
I got the following error:
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at file:///Users/xxx/.npm/_npx/b2f20a89f1590ca0/node_modules/@pkgdeps/update-github-actions-permissions/module/index.js:43:14
    at Array.flatMap (<anonymous>)
    at collectUsesActions (file:///Users/xxx/.npm/_npx/b2f20a89f1590ca0/node_modules/@pkgdeps/update-github-actions-permissions/module/index.js:41:82)
    at computePermissions (file:///Users/xxx/.npm/_npx/b2f20a89f1590ca0/node_modules/@pkgdeps/update-github-actions-permissions/module/index.js:149:25)
    at async updateGitHubActions (file:///Users/xxx/.npm/_npx/b2f20a89f1590ca0/node_modules/@pkgdeps/update-github-actions-permissions/module/index.js:204:33)
    at async run (file:///Users/xxx/.npm/_npx/b2f20a89f1590ca0/node_modules/@pkgdeps/update-github-actions-permissions/module/cli.js:54:32)
```

Input workflow file:
```
name: Build books

on:
  push:

jobs:
  build:
    if: ${{ startsWith(github.head_ref, 'release/') }}
    uses: ./.github/workflows/reusable-build.yml
```

Using version is v2.3.0
